// <auto-generated />
// This file was generated by a T4 template.
// Don't change it directly as your change would get overwritten.  Instead, make changes
// to the .tt file (i.e. the T4 template) and save it to regenerate this file.

// Make sure the compiler doesn't complain about missing Xml comments and CLS compliance
// 0108: suppress "Foo hides inherited member Foo. Use the new keyword if hiding was intended." when a controller and its abstract parent are both processed
#pragma warning disable 1591, 3008, 3009, 0108
#region T4MVC

using System;
using System.Diagnostics;
using System.CodeDom.Compiler;
using System.Collections.Generic;
using System.Linq;
using System.Runtime.CompilerServices;
using System.Threading.Tasks;
using System.Web;
using System.Web.Hosting;
using System.Web.Mvc;
using System.Web.Mvc.Ajax;
using System.Web.Mvc.Html;
using System.Web.Routing;
using T4MVC;
namespace Stagio.Web.Controllers
{
    public partial class InternshipOfferController
    {
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        protected InternshipOfferController(Dummy d) { }

        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        protected RedirectToRouteResult RedirectToAction(ActionResult result)
        {
            var callInfo = result.GetT4MVCResult();
            return RedirectToRoute(callInfo.RouteValueDictionary);
        }

        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        protected RedirectToRouteResult RedirectToAction(Task<ActionResult> taskResult)
        {
            return RedirectToAction(taskResult.Result);
        }

        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        protected RedirectToRouteResult RedirectToActionPermanent(ActionResult result)
        {
            var callInfo = result.GetT4MVCResult();
            return RedirectToRoutePermanent(callInfo.RouteValueDictionary);
        }

        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        protected RedirectToRouteResult RedirectToActionPermanent(Task<ActionResult> taskResult)
        {
            return RedirectToActionPermanent(taskResult.Result);
        }

        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public virtual System.Web.Mvc.ActionResult ValidateOffer()
        {
            return new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.ValidateOffer);
        }
        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public virtual System.Web.Mvc.ActionResult SaveDraft()
        {
            return new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.SaveDraft);
        }
        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public virtual System.Web.Mvc.ActionResult Edit()
        {
            return new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.Edit);
        }
        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public virtual System.Web.Mvc.ActionResult Details()
        {
            return new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.Details);
        }
        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public virtual System.Web.Mvc.ActionResult DeleteDraft()
        {
            return new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.DeleteDraft);
        }
        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public virtual System.Web.Mvc.ActionResult DownloadFile()
        {
            return new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.DownloadFile);
        }

        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public InternshipOfferController Actions { get { return MVC.InternshipOffer; } }
        [GeneratedCode("T4MVC", "2.0")]
        public readonly string Area = "";
        [GeneratedCode("T4MVC", "2.0")]
        public readonly string Name = "InternshipOffer";
        [GeneratedCode("T4MVC", "2.0")]
        public const string NameConst = "InternshipOffer";

        static readonly ActionNamesClass s_actions = new ActionNamesClass();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionNamesClass ActionNames { get { return s_actions; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionNamesClass
        {
            public readonly string StudentIndex = "StudentIndex";
            public readonly string CoordinatorIndex = "CoordinatorIndex";
            public readonly string EmployeeIndex = "EmployeeIndex";
            public readonly string EmployeePublicatedOffersIndex = "EmployeePublicatedOffersIndex";
            public readonly string CoordinatorPublicatedOffersIndex = "CoordinatorPublicatedOffersIndex";
            public readonly string ValidateOffer = "ValidateOffer";
            public readonly string Create = "Create";
            public readonly string SaveDraft = "Create";
            public readonly string Edit = "Edit";
            public readonly string Details = "Details";
            public readonly string DeleteDraft = "DeleteDraft";
            public readonly string DownloadFile = "DownloadFile";
        }

        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionNameConstants
        {
            public const string StudentIndex = "StudentIndex";
            public const string CoordinatorIndex = "CoordinatorIndex";
            public const string EmployeeIndex = "EmployeeIndex";
            public const string EmployeePublicatedOffersIndex = "EmployeePublicatedOffersIndex";
            public const string CoordinatorPublicatedOffersIndex = "CoordinatorPublicatedOffersIndex";
            public const string ValidateOffer = "ValidateOffer";
            public const string Create = "Create";
            public const string SaveDraft = "Create";
            public const string Edit = "Edit";
            public const string Details = "Details";
            public const string DeleteDraft = "DeleteDraft";
            public const string DownloadFile = "DownloadFile";
        }


        static readonly ActionParamsClass_ValidateOffer s_params_ValidateOffer = new ActionParamsClass_ValidateOffer();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_ValidateOffer ValidateOfferParams { get { return s_params_ValidateOffer; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_ValidateOffer
        {
            public readonly string id = "id";
        }
        static readonly ActionParamsClass_Create s_params_Create = new ActionParamsClass_Create();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_Create CreateParams { get { return s_params_Create; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_Create
        {
            public readonly string internshipOfferViewModel = "internshipOfferViewModel";
        }
        static readonly ActionParamsClass_SaveDraft s_params_SaveDraft = new ActionParamsClass_SaveDraft();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_SaveDraft SaveDraftParams { get { return s_params_SaveDraft; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_SaveDraft
        {
            public readonly string _internshipOfferViewModel = "_internshipOfferViewModel";
        }
        static readonly ActionParamsClass_Edit s_params_Edit = new ActionParamsClass_Edit();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_Edit EditParams { get { return s_params_Edit; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_Edit
        {
            public readonly string offerId = "offerId";
        }
        static readonly ActionParamsClass_Details s_params_Details = new ActionParamsClass_Details();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_Details DetailsParams { get { return s_params_Details; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_Details
        {
            public readonly string offerId = "offerId";
            public readonly string offerVm = "offerVm";
        }
        static readonly ActionParamsClass_DeleteDraft s_params_DeleteDraft = new ActionParamsClass_DeleteDraft();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_DeleteDraft DeleteDraftParams { get { return s_params_DeleteDraft; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_DeleteDraft
        {
            public readonly string internshipOfferViewModel = "internshipOfferViewModel";
        }
        static readonly ActionParamsClass_DownloadFile s_params_DownloadFile = new ActionParamsClass_DownloadFile();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_DownloadFile DownloadFileParams { get { return s_params_DownloadFile; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_DownloadFile
        {
            public readonly string pathToExtraFile = "pathToExtraFile";
            public readonly string offerId = "offerId";
        }
        static readonly ViewsClass s_views = new ViewsClass();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ViewsClass Views { get { return s_views; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ViewsClass
        {
            static readonly _ViewNamesClass s_ViewNames = new _ViewNamesClass();
            public _ViewNamesClass ViewNames { get { return s_ViewNames; } }
            public class _ViewNamesClass
            {
                public readonly string _CoordinatorIndexMainPartial = "_CoordinatorIndexMainPartial";
                public readonly string _EmployeeIndexMainPartial = "_EmployeeIndexMainPartial";
                public readonly string _IndexTablePartial = "_IndexTablePartial";
                public readonly string Create = "Create";
                public readonly string Details = "Details";
                public readonly string Index = "Index";
            }
            public readonly string _CoordinatorIndexMainPartial = "~/Views/InternshipOffer/_CoordinatorIndexMainPartial.cshtml";
            public readonly string _EmployeeIndexMainPartial = "~/Views/InternshipOffer/_EmployeeIndexMainPartial.cshtml";
            public readonly string _IndexTablePartial = "~/Views/InternshipOffer/_IndexTablePartial.cshtml";
            public readonly string Create = "~/Views/InternshipOffer/Create.cshtml";
            public readonly string Details = "~/Views/InternshipOffer/Details.cshtml";
            public readonly string Index = "~/Views/InternshipOffer/Index.cshtml";
        }
    }

    [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
    public partial class T4MVC_InternshipOfferController : Stagio.Web.Controllers.InternshipOfferController
    {
        public T4MVC_InternshipOfferController() : base(Dummy.Instance) { }

        [NonAction]
        partial void StudentIndexOverride(T4MVC_System_Web_Mvc_ActionResult callInfo);

        [NonAction]
        public override System.Web.Mvc.ActionResult StudentIndex()
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.StudentIndex);
            StudentIndexOverride(callInfo);
            return callInfo;
        }

        [NonAction]
        partial void CoordinatorIndexOverride(T4MVC_System_Web_Mvc_ActionResult callInfo);

        [NonAction]
        public override System.Web.Mvc.ActionResult CoordinatorIndex()
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.CoordinatorIndex);
            CoordinatorIndexOverride(callInfo);
            return callInfo;
        }

        [NonAction]
        partial void EmployeeIndexOverride(T4MVC_System_Web_Mvc_ActionResult callInfo);

        [NonAction]
        public override System.Web.Mvc.ActionResult EmployeeIndex()
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.EmployeeIndex);
            EmployeeIndexOverride(callInfo);
            return callInfo;
        }

        [NonAction]
        partial void EmployeePublicatedOffersIndexOverride(T4MVC_System_Web_Mvc_ActionResult callInfo);

        [NonAction]
        public override System.Web.Mvc.ActionResult EmployeePublicatedOffersIndex()
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.EmployeePublicatedOffersIndex);
            EmployeePublicatedOffersIndexOverride(callInfo);
            return callInfo;
        }

        [NonAction]
        partial void CoordinatorPublicatedOffersIndexOverride(T4MVC_System_Web_Mvc_ActionResult callInfo);

        [NonAction]
        public override System.Web.Mvc.ActionResult CoordinatorPublicatedOffersIndex()
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.CoordinatorPublicatedOffersIndex);
            CoordinatorPublicatedOffersIndexOverride(callInfo);
            return callInfo;
        }

        [NonAction]
        partial void ValidateOfferOverride(T4MVC_System_Web_Mvc_ActionResult callInfo, int id);

        [NonAction]
        public override System.Web.Mvc.ActionResult ValidateOffer(int id)
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.ValidateOffer);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "id", id);
            ValidateOfferOverride(callInfo, id);
            return callInfo;
        }

        [NonAction]
        partial void CreateOverride(T4MVC_System_Web_Mvc_ActionResult callInfo);

        [NonAction]
        public override System.Web.Mvc.ActionResult Create()
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.Create);
            CreateOverride(callInfo);
            return callInfo;
        }

        [NonAction]
        partial void CreateOverride(T4MVC_System_Web_Mvc_ActionResult callInfo, Stagio.Web.ViewModels.InternshipOffer.Create internshipOfferViewModel);

        [NonAction]
        public override System.Web.Mvc.ActionResult Create(Stagio.Web.ViewModels.InternshipOffer.Create internshipOfferViewModel)
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.Create);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "internshipOfferViewModel", internshipOfferViewModel);
            CreateOverride(callInfo, internshipOfferViewModel);
            return callInfo;
        }

        [NonAction]
        partial void SaveDraftOverride(T4MVC_System_Web_Mvc_ActionResult callInfo, Stagio.Web.ViewModels.InternshipOffer.Create _internshipOfferViewModel);

        [NonAction]
        public override System.Web.Mvc.ActionResult SaveDraft(Stagio.Web.ViewModels.InternshipOffer.Create _internshipOfferViewModel)
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.SaveDraft);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "_internshipOfferViewModel", _internshipOfferViewModel);
            SaveDraftOverride(callInfo, _internshipOfferViewModel);
            return callInfo;
        }

        [NonAction]
        partial void EditOverride(T4MVC_System_Web_Mvc_ActionResult callInfo, int offerId);

        [NonAction]
        public override System.Web.Mvc.ActionResult Edit(int offerId)
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.Edit);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "offerId", offerId);
            EditOverride(callInfo, offerId);
            return callInfo;
        }

        [NonAction]
        partial void DetailsOverride(T4MVC_System_Web_Mvc_ActionResult callInfo, int offerId);

        [NonAction]
        public override System.Web.Mvc.ActionResult Details(int offerId)
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.Details);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "offerId", offerId);
            DetailsOverride(callInfo, offerId);
            return callInfo;
        }

        [NonAction]
        partial void DetailsOverride(T4MVC_System_Web_Mvc_ActionResult callInfo, Stagio.Web.ViewModels.InternshipOffer.FullOffer offerVm);

        [NonAction]
        public override System.Web.Mvc.ActionResult Details(Stagio.Web.ViewModels.InternshipOffer.FullOffer offerVm)
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.Details);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "offerVm", offerVm);
            DetailsOverride(callInfo, offerVm);
            return callInfo;
        }

        [NonAction]
        partial void DeleteDraftOverride(T4MVC_System_Web_Mvc_ActionResult callInfo, Stagio.Web.ViewModels.InternshipOffer.Create internshipOfferViewModel);

        [NonAction]
        public override System.Web.Mvc.ActionResult DeleteDraft(Stagio.Web.ViewModels.InternshipOffer.Create internshipOfferViewModel)
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.DeleteDraft);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "internshipOfferViewModel", internshipOfferViewModel);
            DeleteDraftOverride(callInfo, internshipOfferViewModel);
            return callInfo;
        }

        [NonAction]
        partial void DownloadFileOverride(T4MVC_System_Web_Mvc_ActionResult callInfo, string pathToExtraFile, int offerId);

        [NonAction]
        public override System.Web.Mvc.ActionResult DownloadFile(string pathToExtraFile, int offerId)
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.DownloadFile);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "pathToExtraFile", pathToExtraFile);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "offerId", offerId);
            DownloadFileOverride(callInfo, pathToExtraFile, offerId);
            return callInfo;
        }

    }
}

#endregion T4MVC
#pragma warning restore 1591, 3008, 3009, 0108
